Repository gridscale/terraform-provider-gridscale, pull requests merged in 2019-12, with the labels that each got.

#33 Fix server resource
  gridscale/common.go
  gridscale/config.go
  gridscale/resource_gridscale_ipv4.go
  gridscale/resource_gridscale_network.go
  gridscale/resource_gridscale_server.go
  gridscale/resource_gridscale_storage.go
  gridscale/server_concurrency_handler.go
  website/docs/r/server.html.md
Labels: documentation, size/XL

#35 GitLab CI: run acceptance tests with TF_LOG=DEBUG
  .gitlab-ci.yml
Labels: size/XS

#36 Fix minor bugs
  gridscale/resource_gridscale_ipv4.go
  gridscale/resource_gridscale_ipv6.go
  gridscale/resource_gridscale_loadbalancer.go
  gridscale/resource_gridscale_network.go
  gridscale/resource_gridscale_server.go
  gridscale/resource_gridscale_server_test.go
  gridscale/resource_gridscale_storage.go
  website/docs/r/ipv4.html.md
  website/docs/r/ipv6.html.md
  website/docs/r/loadbalancer.html.md
  website/docs/r/network.html.md
  website/docs/r/server.html.md
  website/docs/r/storage.html.md
Labels: documentation, size/M

#37 Implement storage snapshot
  gridscale/datasource_gridscale_snapshot.go
  gridscale/datasource_gridscale_snapshot_test.go
  gridscale/provider.go
  gridscale/resource_gridscale_snapshot.go
  gridscale/resource_gridscale_snapshot_test.go
  website/docs/d/snapshot.html.md
  website/docs/r/snapshot.html.md
Labels: documentation, size/XL

#31 Implement paas
  gridscale/common.go
  gridscale/datasource_gridscale_paas.go
  gridscale/datasource_gridscale_paas_test.go
  gridscale/provider.go
  gridscale/resource_gridscale_paas.go
  gridscale/resource_gridscale_paas_test.go
  website/docs/d/paas.html.md
  website/docs/r/paas.html.md
Labels: documentation, size/XL

#34 Add paas security zone
  gridscale/datasource_gridscale_securityzone.go
  gridscale/datasource_gridscale_securityzone_test.go
  gridscale/provider.go
  gridscale/resource_gridscale_securityzone.go
  gridscale/resource_gridscale_securityzone_test.go
  website/docs/d/securityzone.html.md
  website/docs/r/securityzone.html.md
Labels: documentation, size/XL

#42 Remove interpolation expressions
  gridscale/datasource_gridscale_ipv4_test.go
  gridscale/datasource_gridscale_ipv6_test.go
  gridscale/datasource_gridscale_loadbalancer_test.go
  gridscale/datasource_gridscale_network_test.go
  gridscale/datasource_gridscale_paas_test.go
  gridscale/datasource_gridscale_securityzone_test.go
  gridscale/datasource_gridscale_snapshot_test.go
  gridscale/datasource_gridscale_snapshotschedule_test.go
  gridscale/datasource_gridscale_sshkey_test.go
  gridscale/datasource_gridscale_storage_test.go
  gridscale/resource_gridscale_loadbalancer_test.go
  gridscale/resource_gridscale_server_test.go
  gridscale/resource_gridscale_snapshot_test.go
  gridscale/resource_gridscale_snapshotschedule_test.go
  gridscale/resource_gridscale_storage_test.go
  website/docs/d/ip.html.md
  website/docs/d/network.html.md
  website/docs/d/paas.html.md
  website/docs/d/publicnetwork.html.md
  website/docs/d/securityzone.html.md
  website/docs/d/snapshot.html.md
  website/docs/d/snapshotschedule.html.md
  website/docs/d/sshkey.html.md
  website/docs/d/storage.html.md
  website/docs/d/template.html.md
  website/docs/index.html.markdown
  website/docs/r/loadbalancer.html.md
  website/docs/r/server.html.md
  website/docs/r/snapshot.html.md
  website/docs/r/snapshotschedule.html.md
  website/docs/r/storage.html.md
Labels: documentation, size/M

#43 Documentation cleanups
  README.md
  website/docs/d/securityzone.html.md
  website/docs/r/loadbalancer.html.md
  website/docs/r/server.html.md
  website/docs/r/storage.html.md
Labels: documentation, size/M
