Repository gridscale/terraform-provider-gridscale, pull requests merged in 2019-10, with the labels that each got.

#16 Added link to the online documentation to README
  README.md
Labels: size/XS

#18 Fix type mismatched
  gridscale/datasource_gridscale_ipv4.go
  gridscale/datasource_gridscale_ipv6.go
  gridscale/datasource_gridscale_network.go
  gridscale/datasource_gridscale_sshkey.go
  gridscale/datasource_gridscale_storage.go
  gridscale/resource_gridscale_ipv4.go
  gridscale/resource_gridscale_network.go
  gridscale/resource_gridscale_server.go
  gridscale/resource_gridscale_sshkey.go
  gridscale/resource_gridscale_storage.go
Labels: size/S

#20 Documentation fixes
  .github/ISSUE_TEMPLATE.md
  .travis.yml
  vendor/github.com/hashicorp/hcl/README.md
  vendor/github.com/hashicorp/hcl2/ext/dynblock/README.md
  vendor/github.com/hashicorp/hcl2/ext/typeexpr/README.md
  website/docs/d/ip.html.md
  website/docs/d/network.html.md
  website/docs/d/sshkey.html.md
  website/docs/d/storage.html.md
  website/docs/d/template.html.md
  website/docs/index.html.markdown
  website/docs/r/ipv4.html.md
  website/docs/r/ipv6.html.md
  website/docs/r/network.html.md
  website/docs/r/server.html.md
  website/docs/r/sshkey.html.md
  website/docs/r/storage.html.md
Labels: dependencies, documentation, size/M

#21 Link to gridscale Terraform examples
  website/docs/index.html.markdown
Labels: documentation, size/XS

#23 Fix minor bugs
  gridscale/resource_gridscale_loadbalancer.go
Labels: size/XS

#22 Update docs and coding convention
  gridscale/datasource_gridscale_ipv4_test.go
  gridscale/datasource_gridscale_ipv6_test.go
  gridscale/datasource_gridscale_loadbalancer_test.go
  gridscale/datasource_gridscale_network_test.go
  gridscale/datasource_gridscale_sshkey_test.go
  gridscale/datasource_gridscale_storage_test.go
  gridscale/resource_gridscale_ipv4_test.go
  gridscale/resource_gridscale_ipv6_test.go
  gridscale/resource_gridscale_loadbalancer_test.go
  gridscale/resource_gridscale_network_test.go
  gridscale/resource_gridscale_server_test.go
  gridscale/resource_gridscale_sshkey_test.go
  gridscale/resource_gridscale_storage_test.go
  website/docs/d/ip.html.md
  website/docs/d/loadbalancer.html.md
  website/docs/d/network.html.md
  website/docs/d/sshkey.html.md
  website/docs/d/storage.html.md
  website/docs/d/template.html.md
  website/docs/r/loadbalancer.html.md
Labels: documentation, size/XL

#24 Update CHANGELOG for release 1.3.0
  CHANGELOG.md
Labels: size/XS

#25 Reimplement server resource
  gridscale/common.go
  gridscale/config.go
  gridscale/relation-manager/serverRelationManager.go
  gridscale/resource_gridscale_ipv4.go
  gridscale/resource_gridscale_network.go
  gridscale/resource_gridscale_server.go
  gridscale/resource_gridscale_server_test.go
  gridscale/resource_gridscale_storage.go
Labels: size/XXL

#27 Update CHANGELOG for release 1.4.0
  CHANGELOG.md
Labels: size/XS
